### ISSUE TITLE
No reproducible. Some folders are missing

### ISSUE THREAD

**Issue by VictorOtin** [PlusLabNLP/Plot-guided-Coherence-Evaluation#2]
Hi,
where are the needed folders for running the repository? In the program, "storyline_manipulation_ROC.py" are imported src.data.data, src.data.config or  src.interactive.functions but in the repo, these folders don't exist. Where could we find them in order to be able to run the repo.

Thanks for your help beforehand :) I just really loved your work in the paper, that's why I want to reproduce it.
Congrats for the amazing project!
Waiting anxiously for your answer,
Victor

**Comment by AIRicky** [comment]
> Hi,
> where are the needed folders for running the repository? In the program, "storyline_manipulation_ROC.py" are imported src.data.data, src.data.config or src.interactive.functions but in the repo, these folders don't exist. Where could we find them in order to be able to run the repo.
> 
> Thanks for your help beforehand :) I just really loved your work in the paper, that's why I want to reproduce it.
> Congrats for the amazing project!
> Waiting anxiously for your answer,
> Victor

Hi,  I run into the same issue, have you solved the problem?

**Comment by SarikGhazarian** [comment]
Thanks for raising this issue. The src folder is from https://github.com/atcbosselut/comet-commonsense code to get the subsequent events used for "Non-logically Ordered Plots" manipulation. Therefore, you need to simply install their Github repo and put the "storyline_manipulation_ROC.py" code in their home directory and try to run it.
